[package]
name = "constructor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
glm = "*"
rand = "0.8"
glam = "0.20"
image = "0.24"
